"""
Configuration file for Neural Network Option Pricing
All file paths and hyperparameters centralized here
"""
import os

# ============================================================
# DIRECTORY PATHS
# ============================================================

# Get project root directory (parent of src/)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Main directories
DATA_DIR = os.path.join(PROJECT_ROOT, 'data', 'raw')
RESULTS_DIR = os.path.join(PROJECT_ROOT, 'results')
MODELS_DIR = os.path.join(PROJECT_ROOT, 'models')

# Create directories if they don't exist
for directory in [DATA_DIR, RESULTS_DIR, MODELS_DIR]:
    os.makedirs(directory, exist_ok=True)

# ============================================================
# INPUT DATA FILES
# ============================================================

# Raw data files (must be placed in data/raw/ before running)
SPX_FORWARD_FILE = os.path.join(DATA_DIR, 'SPX_Forward_Prices_Complete_2018-2025.csv')
SPX_OPTIONS_FILE = os.path.join(DATA_DIR, 'SPX_Options_raw_2018-2025.csv')

# Treasury rates file (created automatically or loaded if exists)
TREASURY_RATES_FILE = os.path.join(DATA_DIR, 'treasury_3month_rates.csv')

# ============================================================
# OUTPUT FILES (Generated by preprocessing)
# ============================================================

# Merged data (created in preprocessing step)
SPX_MERGED_FILE = os.path.join(RESULTS_DIR, 'SPX_MERGED_TO_USE.csv')
SPX_CLEAN_FILE = os.path.join(RESULTS_DIR, 'SPX_Clean_Merged.csv')
SPX_BS_BOTH_FILE = os.path.join(RESULTS_DIR, 'SPX_with_BS_Both_Vols.csv')
SPX_BS_HIST_FILE = os.path.join(RESULTS_DIR, 'SPX_with_BS_Historical.csv')
# Fully engineered feature set used by all models
SPX_FEATURES_FILE = os.path.join(RESULTS_DIR, 'SPX_features.csv')

# Neural network predictions
TEST_PREDICTIONS_FILE = os.path.join(RESULTS_DIR, 'test_predictions_comparison.csv')

# Saved models
MODEL_BASIC_FILE = os.path.join(MODELS_DIR, 'best_NN_Basic.pth')
MODEL_FULL_FILE = os.path.join(MODELS_DIR, 'best_NN_Full.pth')

# ============================================================
# DATA FILTERING PARAMETERS (Hutchinson et al. 1994)
# ============================================================

FILTER_CONFIG = {
    'moneyness_min': 0.80,
    'moneyness_max': 1.20,
    'min_volume': 10,
    'min_open_interest': 100,
    'min_impl_vol': 0.05,
    'max_impl_vol': 1.0,
    'min_maturity': 0.001,  # ~1 day
    'max_maturity': 2.0,     # 2 years
    'min_price': 0.01,       # At least 1 cent
}

# ============================================================
# TRAIN/VAL/TEST SPLIT (Temporal)
# ============================================================

SPLIT_CONFIG = {
    'train_ratio': 0.70,
    'val_ratio': 0.15,
    'test_ratio': 0.15,
}

# ============================================================
# NEURAL NETWORK HYPERPARAMETERS
# ============================================================

NN_CONFIG = {
    'hidden_sizes': [128, 64, 32],
    'dropout_rate': 0.2,
    'learning_rate': 0.001,
    'weight_decay': 1e-5,
    'batch_size': 2048,
    'num_epochs': 300,
    'patience': 30,
}

# ============================================================
# FEATURE SETS
# ============================================================

# Basic features (no market signals)
FEATURES_BASIC = [
    'moneyness',
    'log_moneyness',
    'T',
    'log_T',
    'sqrt_T',
    'is_call',
    'forward_price_norm',
    'moneyness_T',
    'log_moneyness_sqrt_T',
    'log_volume',
    'log_open_interest',
    'bid_ask_spread',
    'historical_vol',
    'historical_vol_sqrt_T'
]

# Full features (includes implied vol and Greeks)
FEATURES_FULL = FEATURES_BASIC + [
    'impl_vol',
    'impl_vol_sqrt_T',
    'impl_vol_squared',
    'abs_delta',
    'gamma_norm',
    'vega_norm',
    'theta_norm',
    'gamma_delta_ratio',
    'vega_T',
]

# ============================================================
# TREASURY RATES CONFIGURATION
# ============================================================

TREASURY_CONFIG = {
    'symbol': 'DTB3',  # 3-Month Treasury Bill Rate
    'source': 'fred',
    'start_date': '2017-12-01',
    'end_date': '2025-12-31',
    'fallback_rate': 0.04,  # 4% if data unavailable
}

# ============================================================
# BLACK-SCHOLES BASELINE
# ============================================================

BS_CONFIG = {
    'historical_vol_window': 60,  # 60-day rolling window
    'trading_days_per_year': 252,
}

print(f"✅ Configuration loaded")
print(f"   Project root: {PROJECT_ROOT}")
print(f"   Data directory: {DATA_DIR}")
print(f"   Results directory: {RESULTS_DIR}")
